sudo: false
language: node_js
node_js:
  - "0.12"

after_success:
  "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

env:
  global:
    - secure: SF/VM+H5FQ6v7WGtRSNsWpCWad4KBN4NlGw+E6vkE2viO3/yj/TkF2pIqLEys4+x0uhtiVbnRIuFwLx/5BDAY3aQ+abWphi7v1/wqDDs4O9OhMe/BWdxBwxd7TETl5uO0XFIOgYe73y/NXbf8aimp0H+IBqkO6Nl4zTRTBclHCE=
    - secure: EnVqtfiBuO+M45UQxyqZtArDOcVSY57GolYGYtnXI8uRddxbMIQqtGFgcptUeAxwvf2qQgdVwvsV/ujHWXmdPGlwxuAf65qD1PyNqIg4PPBDp/0PVpVHPFTuvU0SzwIDHLxAIRqk7CF8wZwmCz/dIsu8UlM47YmQ2pAeqhIUDvQ=
