sudo: false
language: node_js
node_js:
  - "0.12"

after_success:
  "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

addons:
  sauce_connect: true
env:
  global:
    - secure: gbI+ipNLsOxBGKTp/wDIQnDLKMKZz8jGkIO8xDe9S5xmJRehCavJ827Oaga6sWXXJsK3o69uBh1c1pZO/MWx4JCTYUyUlMgjbxP2NHtcnsgkdnpe4+8Q6XFSc8AvlHeU3Kj2SmAqY9qGYzeMwtPc2pzuZRVsViVCXlLCRiZr5X4=
    - secure: Qj2QoTWVGKjdWfc0NzAVdIVk4ZDmz7PgV8bHfG/B5Y9CEeafPH+IOjbqraJXsCbvwv3VkZTz4Fpk258ksuwDSyfySJJTnyI96xagkTDB2a4g9SepEeMktCAbqXygiOge9vToDYUmhhVkJ250piyyR9eNg29I+0ZQpmM5nNQUR5c=
