name: browser-cookies
ui: jasmine
browsers:
  - name: android
    version: oldest
  - name: android
    version: latest
  - name: iphone
    version: oldest
  - name: iphone
    version: latest
  - name: chrome
    version: oldest
  - name: chrome
    version: latest
  - name: firefox
    version: oldest
  - name: firefox
    version: latest
  - name: internet explorer
    version: 6
  - name: internet explorer
    version: 7
  - name: internet explorer
    version: 8
  - name: internet explorer
    version: 9
  - name: internet explorer
    version: 10
  - name: internet explorer
    version: 11
  - name: microsoftedge
    version: oldest
  - name: microsoftedge
    version: latest
  - name: opera
    version: oldest
  - name: opera
    version: latest
  - name: safari
    version: oldest
  - name: safari
    version: 7
  - name: safari
    version: latest
scripts:
  - "dist/browser-cookies.test.js"
