name: browser-cookies
ui: jasmine
tunnel:
  type: ngrok
  bind_tls: false
concurrency: 1
scripts:
  - "dist/browser-cookies.test.js"
browsers:
  - name: iphone
    version: oldest
  - name: iphone
    version: latest
  - name: chrome
    version: oldest
  - name: chrome
    version: latest
  - name: firefox
    version: oldest
  - name: firefox
    version: latest
  - name: internet explorer
    version: oldest
  - name: internet explorer
    version: lateste
  - name: MicrosoftEdge
    version: oldest
  - name: MicrosoftEdge
    version: latest
  - name: safari
    version: oldest
  - name: safari
    version: latest
